apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    group: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata: 
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: itssvinayak/url_shortner:latest
          imagePullPolicy: Always
          # setting up the environment variables for the container but we will use config maps for this as we are 10x developer
          # env:
          #   - name: REDIS_HOST
          #     value: redis
          #   - name: REDIS_PORT
          #     value: "6379"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10