apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    group: url-shortener
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
