apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-host-path-volume
  labels:
    group: url-shortener
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  # ReadWriteOnce - the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  # ReadOnlyMany - the volume can be mounted read-only by many nodes
  # ReadWriteMany - the volume can be mounted as read-write by many nodes
  hostPath:
    path: /data/redis
    type: DirectoryOrCreate