apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    group: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata: 
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine