apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-host-path-volume-claim
  labels:
    group: url-shortener
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storageClassName: standard 
  volumeName: redis-data-host-path-volume
