apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  # labels are used to group the resources
  labels:
    group: url-shortener
spec:
  selector:
    # this is the label of the pod
    app: url-shortener
  ports:
    - protocol: TCP
      # this is the port of the container for outside world
      port: 8080
      # this is the port of the container
      targetPort: 8080
  # LoadBalancer - exposes the service externally using cloud provider's load balancer
  # NodePort - exposes the service on the same port of each selected Node in the cluster using NAT
  # ClusterIP - exposes the service on a cluster-internal IP
  type: LoadBalancer
