apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    group: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata: 
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: itssvinayak/url_shortner:latest
          imagePullPolicy: Always
          # setting up the environment variables for the container but we will use config maps for this as we are 10x developer
          env:
            - name: REDIS_URL
            # redis service name is redis-service, this can be found in the redis-service.yaml file , with multiple namespaces we can use the namespace name as well redis://redis-service.default:6379 for getting namespace, kubectl get namespace
              value: "redis://redis-service:6379"
          # this is pod-to-pod communication
          # for within the pod, localhost network is used
          # for outside the pod, the service name is used
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10